# Generated by Django 4.2.4 on 2024-11-23 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_test_table_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Father_name', models.CharField(max_length=10)),
                ('Mother_name', models.CharField(max_length=10)),
                ('Nationality', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='test_table',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Female', max_length=6),
        ),
        migrations.AddField(
            model_name='test_table',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.main_test'),
        ),
    ]
