# Generated by Django 5.1.3 on 2024-12-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_customuser_is_verified_customuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='def.png', max_length=255, null=True, upload_to='profile_image/'),
        ),
    ]
